//
//  Shared.swift
//  shuzhai2
//
//  Created by VincentHe on 6/30/15.
//  Copyright (c) 2015 VincentHe. All rights reserved.
//

import UIKit
import Alamofire
import AlamofireObjectMapper
import JavaScriptCore


struct GlobalVariables {
    static var dailyStoryUrl = "http://104.131.79.31/onebook/book/getSingleRecommendationBook.form"
    static var mutilStoryUrl = "http://104.131.79.31/onebook/book/getMultipleRecommendationBook.form"
    static var baiduOCRUrl = "http://apis.baidu.com/apistore/idlocr/ocr"
    static var readingFetchDefaultNumb = 5
    static var defaultColorGroup = [UIColor.peterRiverColor(),UIColor.carrotColor(),UIColor.nephritisColor(),UIColor.sunflowerColor(),UIColor.wisteriaColor(),UIColor.midnightBlueColor(),UIColor.turquoiseColor()]
}


enum Router: URLRequestConvertible {
    static let baseUrlString = "someUrl"
    
    case Get(url: String)
    
    var URLRequest: NSURLRequest {
        let path: String = {
            switch self {
            case .Get(let url):
                return "/\(url)"
            }
            }()
        
        let URL = NSURL(string: Router.baseUrlString)!
        let URLRequest = NSMutableURLRequest(URL:
            URL.URLByAppendingPathComponent(path))
        
        // set header fields
        URLRequest.setValue("application/json",
            forHTTPHeaderField: "Content-Type")
        URLRequest.setValue("application/json",
            forHTTPHeaderField: "Accept")
        
        return URLRequest.0
    }
}

class DataManager: NSObject {
    static func fetchTodayBook(completionHandler:(DailyReading?,NSError?)->Void){
        
        Alamofire.request(.POST, GlobalVariables.dailyStoryUrl, parameters: ["requestDate": "2015-06-17"])
            .responseObject { (response: DailyReading?, error: NSError?) in
                
                if response != nil
                {
                    completionHandler(response,nil)
                }else
                {
                    completionHandler(nil,error)
                }
        }
    
    }
    
    static func fetchNumberOfBooks(completionHandler:([DailyReading]?,NSError?)->Void){
        
        let calendar = NSCalendar.currentCalendar()
        let today = calendar.dateByAddingUnit(.CalendarUnitDay, value: 0, toDate: NSDate(), options: nil)
        let ndaysAgo = calendar.dateByAddingUnit(.CalendarUnitDay, value: -GlobalVariables.readingFetchDefaultNumb, toDate: NSDate(), options: nil)
        
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd" // superset of OP's format
        let todayStr = dateFormatter.stringFromDate(today!)
        let ndaysAgoStr = dateFormatter.stringFromDate(ndaysAgo!)
        
        Alamofire.request(.POST, GlobalVariables.mutilStoryUrl, parameters: ["startDate": ndaysAgoStr,"endDate":todayStr])
            .responseArray { (response: [DailyReading]?, error: NSError?) in
                
                if response != nil
                {
                    completionHandler(response,nil)
                }else
                {
                    completionHandler(nil,error)
                }
        }
    }
    
    static func fetchResultFromBaiduOCR(image:UIImage,completionHandler:(BaiduOCRResponse?,NSError?)->Void){
        
        var base64String:String = image.autoResizeToDataWithSize800x600.base64EncodedStringWithOptions(NSDataBase64EncodingOptions.allZeros)
        base64String = "/9j/4AAQSkZJRgABAQEASABIAAD/4QCARXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAACQAAAAAQAAAJAAAAABAAKgAgAEAAAAAQAAAPKgAwAEAAAAAQAAACgAAAAA/+EJIWh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS40LjAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPD94cGFja2V0IGVuZD0idyI/PgD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/+IPRElDQ19QUk9GSUxFAAEBAAAPNGFwcGwCEAAAbW50clJHQiBYWVogB98AAwAKAAAAAAArYWNzcEFQUEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1hcHBsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARZGVzYwAAAVAAAABiZHNjbQAAAbQAAAQaY3BydAAABdAAAAAjd3RwdAAABfQAAAAUclhZWgAABggAAAAUZ1hZWgAABhwAAAAUYlhZWgAABjAAAAAUclRSQwAABkQAAAgMYWFyZwAADlAAAAAgdmNndAAADnAAAAAwbmRpbgAADqAAAAA+Y2hhZAAADuAAAAAsbW1vZAAADwwAAAAoYlRSQwAABkQAAAgMZ1RSQwAABkQAAAgMYWFiZwAADlAAAAAgYWFnZwAADlAAAAAgZGVzYwAAAAAAAAAIRGlzcGxheQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1sdWMAAAAAAAAAIgAAAAxockhSAAAAFAAAAahrb0tSAAAADAAAAbxuYk5PAAAAEgAAAchpZAAAAAAAEgAAAdpodUhVAAAAFAAAAexjc0NaAAAAFgAAAgBkYURLAAAAHAAAAhZ1a1VBAAAAHAAAAjJhcgAAAAAAFAAAAk5pdElUAAAAFAAAAmJyb1JPAAAAEgAAAnZlc0VTAAAAEgAAAnZoZUlMAAAAFgAAAohubE5MAAAAFgAAAp5maUZJAAAAEAAAArR6aFRXAAAADAAAAsR2aVZOAAAADgAAAtBza1NLAAAAFgAAAt56aENOAAAADAAAAsRydVJVAAAAJAAAAvRmckZSAAAAFgAAAxhtcwAAAAAAEgAAAy5jYUVTAAAAGAAAA0B0aFRIAAAADAAAA1hlc1hMAAAAEgAAAnZkZURFAAAAEAAAA2RlblVTAAAAEgAAA3RwdEJSAAAAGAAAA4ZwbFBMAAAAEgAAA55lbEdSAAAAIgAAA7BzdlNFAAAAEAAAA9J0clRSAAAAFAAAA+JqYUpQAAAADgAAA/ZwdFBUAAAAFgAABAQATABDAEQAIAB1ACAAYgBvAGoAac7st+wAIABMAEMARABGAGEAcgBnAGUALQBMAEMARABMAEMARAAgAFcAYQByAG4AYQBTAHoA7QBuAGUAcwAgAEwAQwBEAEIAYQByAGUAdgBuAP0AIABMAEMARABMAEMARAAtAGYAYQByAHYAZQBzAGsA5gByAG0EGgQ+BDsETAQ+BEAEPgQyBDgEOQAgAEwAQwBEIA8ATABDAEQAIAZFBkQGSAZGBikATABDAEQAIABjAG8AbABvAHIAaQBMAEMARAAgAGMAbwBsAG8AciAPAEwAQwBEACAF5gXRBeIF1QXgBdkASwBsAGUAdQByAGUAbgAtAEwAQwBEAFYA5AByAGkALQBMAEMARF9pgnIAIABMAEMARABMAEMARAAgAE0A4AB1AEYAYQByAGUAYgBuAOkAIABMAEMARAQmBDIENQRCBD0EPgQ5ACAEFgQaAC0ENAQ4BEEEPwQ7BDUEOQBMAEMARAAgAGMAbwB1AGwAZQB1AHIAVwBhAHIAbgBhACAATABDAEQATABDAEQAIABlAG4AIABjAG8AbABvAHIATABDAEQAIA4qDjUARgBhAHIAYgAtAEwAQwBEAEMAbwBsAG8AcgAgAEwAQwBEAEwAQwBEACAAQwBvAGwAbwByAGkAZABvAEsAbwBsAG8AcgAgAEwAQwBEA4gDswPHA8EDyQO8A7cAIAO/A7gDzAO9A7cAIABMAEMARABGAOQAcgBnAC0ATABDAEQAUgBlAG4AawBsAGkAIABMAEMARDCrMOkw/AAgAEwAQwBEAEwAQwBEACAAYQAgAEMAbwByAGUAcwAAdGV4dAAAAABDb3B5cmlnaHQgQXBwbGUgSW5jLiwgMjAxNQAAWFlaIAAAAAAAAPMWAAEAAAABFspYWVogAAAAAAAAccAAADmKAAABZ1hZWiAAAAAAAABhIwAAueYAABP2WFlaIAAAAAAAACPyAAAMkAAAvdBjdXJ2AAAAAAAABAAAAAAFAAoADwAUABkAHgAjACgALQAyADYAOwBAAEUASgBPAFQAWQBeAGMAaABtAHIAdwB8AIEAhgCLAJAAlQCaAJ8AowCoAK0AsgC3ALwAwQDGAMsA0ADVANsA4ADlAOsA8AD2APsBAQEHAQ0BEwEZAR8BJQErATIBOAE+AUUBTAFSAVkBYAFnAW4BdQF8AYMBiwGSAZoBoQGpAbEBuQHBAckB0QHZAeEB6QHyAfoCAwIMAhQCHQImAi8COAJBAksCVAJdAmcCcQJ6AoQCjgKYAqICrAK2AsECywLVAuAC6wL1AwADCwMWAyEDLQM4A0MDTwNaA2YDcgN+A4oDlgOiA64DugPHA9MD4APsA/kEBgQTBCAELQQ7BEgEVQRjBHEEfgSMBJoEqAS2BMQE0wThBPAE/gUNBRwFKwU6BUkFWAVnBXcFhgWWBaYFtQXFBdUF5QX2BgYGFgYnBjcGSAZZBmoGewaMBp0GrwbABtEG4wb1BwcHGQcrBz0HTwdhB3QHhgeZB6wHvwfSB+UH+AgLCB8IMghGCFoIbgiCCJYIqgi+CNII5wj7CRAJJQk6CU8JZAl5CY8JpAm6Cc8J5Qn7ChEKJwo9ClQKagqBCpgKrgrFCtwK8wsLCyILOQtRC2kLgAuYC7ALyAvhC/kMEgwqDEMMXAx1DI4MpwzADNkM8w0NDSYNQA1aDXQNjg2pDcMN3g34DhMOLg5JDmQOfw6bDrYO0g7uDwkPJQ9BD14Peg+WD7MPzw/sEAkQJhBDEGEQfhCbELkQ1xD1ERMRMRFPEW0RjBGqEckR6BIHEiYSRRJkEoQSoxLDEuMTAxMjE0MTYxODE6QTxRPlFAYUJxRJFGoUixStFM4U8BUSFTQVVhV4FZsVvRXgFgMWJhZJFmwWjxayFtYW+hcdF0EXZReJF64X0hf3GBsYQBhlGIoYrxjVGPoZIBlFGWsZkRm3Gd0aBBoqGlEadxqeGsUa7BsUGzsbYxuKG7Ib2hwCHCocUhx7HKMczBz1HR4dRx1wHZkdwx3sHhYeQB5qHpQevh7pHxMfPh9pH5Qfvx/qIBUgQSBsIJggxCDwIRwhSCF1IaEhziH7IiciVSKCIq8i3SMKIzgjZiOUI8Ij8CQfJE0kfCSrJNolCSU4JWgllyXHJfcmJyZXJocmtyboJxgnSSd6J6sn3CgNKD8ocSiiKNQpBik4KWspnSnQKgIqNSpoKpsqzysCKzYraSudK9EsBSw5LG4soizXLQwtQS12Last4S4WLkwugi63Lu4vJC9aL5Evxy/+MDUwbDCkMNsxEjFKMYIxujHyMioyYzKbMtQzDTNGM38zuDPxNCs0ZTSeNNg1EzVNNYc1wjX9Njc2cjauNuk3JDdgN5w31zgUOFA4jDjIOQU5Qjl/Obw5+To2OnQ6sjrvOy07azuqO+g8JzxlPKQ84z0iPWE9oT3gPiA+YD6gPuA/IT9hP6I/4kAjQGRApkDnQSlBakGsQe5CMEJyQrVC90M6Q31DwEQDREdEikTORRJFVUWaRd5GIkZnRqtG8Ec1R3tHwEgFSEtIkUjXSR1JY0mpSfBKN0p9SsRLDEtTS5pL4kwqTHJMuk0CTUpNk03cTiVObk63TwBPSU+TT91QJ1BxULtRBlFQUZtR5lIxUnxSx1MTU19TqlP2VEJUj1TbVShVdVXCVg9WXFapVvdXRFeSV+BYL1h9WMtZGllpWbhaB1pWWqZa9VtFW5Vb5Vw1XIZc1l0nXXhdyV4aXmxevV8PX2Ffs2AFYFdgqmD8YU9homH1YklinGLwY0Njl2PrZEBklGTpZT1lkmXnZj1mkmboZz1nk2fpaD9olmjsaUNpmmnxakhqn2r3a09rp2v/bFdsr20IbWBtuW4SbmtuxG8eb3hv0XArcIZw4HE6cZVx8HJLcqZzAXNdc7h0FHRwdMx1KHWFdeF2Pnabdvh3VnezeBF4bnjMeSp5iXnnekZ6pXsEe2N7wnwhfIF84X1BfaF+AX5ifsJ/I3+Ef+WAR4CogQqBa4HNgjCCkoL0g1eDuoQdhICE44VHhauGDoZyhteHO4efiASIaYjOiTOJmYn+imSKyoswi5aL/IxjjMqNMY2Yjf+OZo7OjzaPnpAGkG6Q1pE/kaiSEZJ6kuOTTZO2lCCUipT0lV+VyZY0lp+XCpd1l+CYTJi4mSSZkJn8mmia1ZtCm6+cHJyJnPedZJ3SnkCerp8dn4uf+qBpoNihR6G2oiailqMGo3aj5qRWpMelOKWpphqmi6b9p26n4KhSqMSpN6mpqhyqj6sCq3Wr6axcrNCtRK24ri2uoa8Wr4uwALB1sOqxYLHWskuywrM4s660JbSctRO1irYBtnm28Ldot+C4WbjRuUq5wro7urW7LrunvCG8m70VvY++Cr6Evv+/er/1wHDA7MFnwePCX8Lbw1jD1MRRxM7FS8XIxkbGw8dBx7/IPci8yTrJuco4yrfLNsu2zDXMtc01zbXONs62zzfPuNA50LrRPNG+0j/SwdNE08bUSdTL1U7V0dZV1tjXXNfg2GTY6Nls2fHadtr724DcBdyK3RDdlt4c3qLfKd+v4DbgveFE4cziU+Lb42Pj6+Rz5PzlhOYN5pbnH+ep6DLovOlG6dDqW+rl63Dr++yG7RHtnO4o7rTvQO/M8Fjw5fFy8f/yjPMZ86f0NPTC9VD13vZt9vv3ivgZ+Kj5OPnH+lf65/t3/Af8mP0p/br+S/7c/23//3BhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAAoOdmNndAAAAAAAAAABAAEAAAAAAAAAAQAAAAEAAAAAAAAAAQAAAAEAAAAAAAAAAQAAbmRpbgAAAAAAAAA2AACnQAAAVYAAAEzAAACewAAAJYAAAAzAAABQAAAAVEAAAjMzAAIzMwACMzMAAAAAAAAAAHNmMzIAAAAAAAEMcgAABfj///MdAAAHugAA/XL///ud///9pAAAA9kAAMBxbW1vZAAAAAAAAAYQAACgDwAAAADJzoyAAAAAAAAAAAAAAAAAAAAAAP/AABEIACgA8gMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2wBDAAICAgICAgMCAgMEAwMDBAUEBAQEBQcFBQUFBQcIBwcHBwcHCAgICAgICAgKCgoKCgoLCwsLCw0NDQ0NDQ0NDQ3/2wBDAQICAgMDAwYDAwYNCQcJDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ3/3QAEABD/2gAMAwEAAhEDEQA/AP3Uoor4t+MPxA/ag+GFxqviy41D4Zaf4Fhv44LO61WLWmvUiupFigFwLUPGrb2Cu4wg6kgV0MwR9LeEfif8P/Hmq67ofhDXLTU9Q8NXj2Gq2sLES2twhKkMrBSV3AqHXKFlZQxKsB3lfnRrHwb/AGpLr4n6V8dXi+F2j+INFtbiO7utPu9agh1O1khKbb8CIeakOA6ZOSVUM21Vxs/Cn4l/tsfGHwfpHxB0Gx+Gml6Hq7yGJL9NYF6YIpmiaUIrsmHClo8sNwwTjNTcdj7+rhvE3xK8C+DvEPh7wp4n1m207VfFVxJa6RbTEhrqaNQzKpAKr1VVLEBnZUXLMAfEv2hvA/xD+IHiz4caB4V1bxHofh9tQ1CTxJfeG9QbTZ4rdLYGDfIp5DSjaBtbqcAHBHxhrvgf4PeMraC28Xal+0RriWdwtxarqdnfXn2a5TIEkReycI4BIyp/kMNsEj9daxfEXiPQfCOiXfiTxPf2+l6XYR+bc3d1IIoYkyBlmbjkkADqSQBya/J3TL7wJ8StT1b4e/CX4p/HG98cx2OoCzs9R1i4trWC+s4JGRL1njj8lTLGI23lfnIUkE5r7Pl8e+DfhJ8A/B2i/tVXyxXGq6Vb6Vqseqwy6wLq9SANPHO0CXKyE7SS7Ehj/ETRcHE+odO1HT9XsLfVdJuYb2yu4kmt7m3kWWGaKQbldHUlWVgcggkEVcr8+vAugfDHw9+zP8Xte+BPizVdY8HahpuuS6XZ3Init9Hlhs5TNFZm4jjn2tI+4uSQcL1cO77vwV/Zj+Evir4O+CvEuuQ65cahq/h/TL28kHiLV4lknuLeOSRtkd2qKCzE4VQB2FFwsfdFR+dFkjeuRwRkcV8i/sOxunwEtjJPPcM2t62u+4laZ9sV7LEo3OS2AqDqTzk96+WtC8Mfs72fi34iP8dPh5rWpa7e+PNdls7oaDq10k9jJNugMUltGY2U4cjHJHPQgkuKx+sCSJJnYwbHBwc4rkh4+8It45b4arqKHxKunDVm08JIXFk0hiExbb5e3eNuN2c445GfzU0q8/4Vh8JP2g/GPwXsNS8EWEGo6Pc+H3uNNms5FjSG2SbZFqERJVpDKDuU43EjGRX0h4dEiftu6hHJK8zD4WWAaSTG+RhqTfM20Ku49TgAc8AUXHY+yWZVGWIA9+KdXwp/wUDj0iX4S+GI9Zjs5om8baMBDf3DWtpICJhIs0y/6uIxbxI+DsXLdQK+Xj4b+A/bwh8DP/DkSf8AyPQ2CifsUroxIVgSOuD0p1fmt+w7baFZ/Fv4zW/hmz0Gw0xU8M+Rb+GdSOr6Umbe53eTdsFMpLZL8Da5Ze1fRn7RngD4E3GkyfFr42DUY7Lw9bRWzXFlfahAI4ppwqjybGVCzNLKAW2k4xk4HBfS4ra2Pp2ivxi8d2PwKvPiL4C0/wABWfj2w8ILPdXfirUCnieRpIY4wbe0SOXfL++cEPJEoKqwO7rj2VdJ/Yf1HVdK0G4h8ZQT65f2+l2X26TxXbRSXd02yKPzLhkjBYnuemSeAaLjsfpxVLUtS0/RtOutX1e5is7GxhkuLm5ncRxQwxKWeR3YgKqqCSTwAK8L8f8AhTTPhd+zX4v8N+ApbzSLbRPDOsy2E0V3M93byCGacOtxI7TbxISQ27I7YwMfmL/wmukWPw18C6j/AMJj8ZtR1vxFdaNYaq11f6wml51CPddNaFIgtyUOVhhRpGlHQOMtQ3YErn7O+GPFHh7xpoNn4o8KahBqmk6gnmW13bNvikUEqcH1DAgg8ggg8it6vxf8Vaf8O/hVp/hHw98KNf8AjHounap4mtbC+tJRremQR2dysrXDWcSW0CyXhKgpGqyM/OUIyR+if7NumeH7Xwxq1/4e13x1rcNzqJjkbx5Jcm+geGNPkgS6ihdYSHDZwcsSCeMATBo+i3ZUUu5CqoJJPAAHUmuD+HHxQ8BfFvw+fFPw71eHWdMWZrZ5oldDHMgVmjdJFR1YKynBUcEHoRXxZ4ruvjV8U/jZ8W/hXpnxdh8DeGtDttIggtpNGsbqR4tYst0yxzu9vOhUqx372YbxtKYFdB4E+D/xa+G3hPTfBHg749eH7DSNKi8m2gXwpYkgElmZmN/l3diWZjksxJJJNFwsfeNcz4p8aeEfA9nb6h4y1mx0O0u7lLOGfULhLaJ7h1ZljDyFV3MqMQM84NfOf7J3jn4heNtM8fw/ELxHD4on8N+M9Q0Gzv4LSCzSS3so4RuWO3G0K7MWGWdhnG4gCvmr9ozxv/wuPx6ZPD7a3L4D+C97DqOrat4btoL26fX96hWgiuAYpYtNjBe4ID43EMu0q9F9BW1P1HyMZrD8PeJ/DXi3T/7W8KatY61Y+Y0X2nT7mO6h8xMbl8yJmXcM8jORX5rfB39pnX9H1bxp4i1Obx/8VfAMtwtnoGtWOhRSx266fbrNfTXSxravCGadQm6MZVD3Bx5B+yhrFjNH8KtZ8C6X42s9Z0/Ur3Q/EWp2GiNe+HL/AE69vZbgW93MJ1SJ4fPjbz9uYwSWVtq4XMPlP2koooqiT//Q/dSuW8beDtB+IPhLVvBPieD7TpetWklpcx9G2SDG5T/C6HDI3VWAI5FdTXxn4k0/9r34q+INS8LJJpPwo8HwXEls2rWFz/amt6hbgkeZaPiNbdZF6M6RTRtyM4xW7MEfJviH4vfEzRdIl/YT17ULaTxbe6hbeG7fxe91AtufDd2uRJOrSbxe/ZsQ+UfmcMPmMhQyfrB4W8N6T4O8NaV4T0KLyNO0azgsbWPOSsNugjQE9zhRk9zzXhek/sl/AnTvh/dfDu98Nw6xa6i/2jUNQ1E+fqt5eENm6kvAFlWfLMQ0ZQLuYKAGIPlkPwz/AGrvgnPFZfCHxVY/EXwkrpHFo/jNmj1Oxh3AbYr+Lb5yqCTmTARVCpE3dLQbs9j3z4n+JPjfomq6bb/CrwbpniWxmhka+n1DVRpxglDAIijY7Nlcknbivk/9pz4l/tTaL8CvE+o33hTSfCcAitoptW0rxE9xe2yT3MUTeUgtYvmcPsLCQFQxYciv0StvtP2aL7Zs+0bF83ys7N+Pm255256Z5xXw9+1Z4e/aQ+Ken6z8G/A/g7S7rwnrg05v+EjuNSit3t/KmSaVHt2kMjFZIh8yoRsbAVjkhsEU/hX4Z+OnwY8HQeGfhv8ABzwvZW7KstxK/ilpbu7nI5luJTZKZHP+9tUfKgCgAfXPw71Dx3rHha2v/iZotnoWvGWfzbGzuReQxIrssTLMByXjwx6Yziu2hjMUMcROSihc/QYouFmeCRLZ1jlZGEbsu9VcjglcruAPJGRn1FFhNn5x/CHV9C1D4HeK/g8dWsrHxR8Rdf8AHelaDbXjyKs8pM+92MaSMkSDq23BbCjLEA5Pg7wV8NdA+Guoz3f7RfjiC2+G8FvpXiRNH1VUstNuYMW5it4GsGm8gyoyQbd+8DCliDWDov7HHxo+GGkSXfgG+0i+8e+NNSu7XX/GEkrJNoOlXDsxl06F1UmadcmaUN5qMwjiXGZ1/QL4b/B3wP8ADL4a2vwt0axjudGS2eC8W6RZTqDzgi4kuQRtkaYk7gRt24UAKAAlqU2jgf2Z/hte/C34K23hrS/Edp4pFxLeanpmqrua2mjv2M8LMwZi6lm3Myn5skjrXyz8atI/aO8SfEr4PeAfF+p+BLvUp9eufEGn/Y9N1Dy4JtDtjLvuRJcnzICZNuFMbb9uDjOPor4LfB/4gfAjU/Gnhrw3dW2r/D6RW1Lwlpd5dSJdWV7PuaWy84xyeXal+jYcjdv2s5kLcj8Pvhl8dpbnxL8fvHUOlt8U9RtGsPDmg3c7S6TommrKHNsZLdyDLcbcvKrNg4OfmdQdLC63PG/jJ8Qfi/4g+Hfx6+FvxD/sPVZ/Cul+Hnt5fDVndRu8mrTCQrJFLNO3yKgJx0X5icHA908Pukv7b+oSRnKv8LLFlPTIOpMR1rqfgt8Pviv4QvviL8TfiSmjXfi3xnPbXMOmaNNKtnHFplr5NtAZ5o94dzkMcOo+8M5Kjkvg1o3xe8XfH7XfjZ8SfBDeA7WTwraeHrOxl1K31KSd0umuXk3QbSgXphkXORjPOADm/wBoDQvE/wAP9BuvGPjv4qa7qGkX+uQwadoVn4b0XUJFnvZmEEFtFdwuZWhjJxyXZUJGScHxP4v2Oo/Bv4g+A9B8UfEOe18OeKrLVLi9vG8F6JcXdm9lHG0KiC20uVyHeUK48ttuOoGSPoD4g/A3xt+0d8U9Sg+LEdz4e+H3hKF4vDMOm3yi61DU7hBjVS8ZPlm2HEUbrw3HKlw3B3/wo/a78LfEzwb42nl0H4o2ngS21Oz06aS6bRdVvINSiWM/bS6SQeZHtUKybiwBLkscgdxpmX8MLjQfHXia58H/AAf+POr2+s3Fq17cRQeCLHS/MgtyF3u76XaK2wygAbs/Nx3r6K/bHjkh/Za8cxNIZpI9Nt1Mj4BdluIfmOMDJPJxXOz/ABi/a8UlIf2eoWx0b/hNNMKn8Cin+Vdr+094S8e/ET9nPxH4U8J6atx4m1a1sU+wxTxbdwuYHuEWWcxoQqK+GO0kDgZwKOgupWt/GX7U3kRbfhr4ZI2Lz/wlUnPA/wCodXzz+0H4h+Neqah8Jbb4ieD9H0HTB8TfDjpdafrbajK04eQKhia0gwpUsdwY4IAxzkfRkPwO+Iqwxg/GjxkpCgFfI0jjjp/yDzXlnxP/AGdfirqup/D6/svHWu+NINC8baNq99ZaudOt7eCztGdpbhTBb27vIg+VUBbO4/LkZAwR9D/tDXEVr8BfiLNMdqL4W1gE4J62koHT3NfCHxg13xd4V/Zm+HUOreCLrWvBuhaR4Sv08QaR4iGjX9nqEUCLE7IbS4aOOOQqPMzwXUgqRkfXf7WPhb4i+PPg9eeAfhrZfabzxHe2Wn38/npCbPTZJlNxNh2XzBtUKyA5KMxGcYPmeqt+1d4hsbz4VeF/hx4P8NeFrOJtFTUfEGo/2raXumRqYA0NnbqjgPEAQk8e3B2kdSBgj5b8eXPjn4fXvgPxT4p8O6/4muLnXrC58L6dN8T/AO2kv78cwzRWzabiWPDhWkUgKJQNwD1+vOnSX0un20uqQx2148MbXEMUhmjjmKguiSFULqrZAYquRzgdK/M7wn+xR8YfgnrGj+PPhb400XxXr+j6fJp8Fl4usJxY2sczl5PsLxTSyW+QzKAoXId8sA5A+1/g/rvxv1u31RfjT4Y0nw5PayQxWLaVffbEvQVJll25YxIDtChm3k7sgAAsIJeR8Q6tZeELz9q/4ynxX8KL34nqkXhnyPsdjZXv2Amw+bcLyaHZ53GNm7PlnOMDPdDRvg8Tj/hlDW//AAQ6L/8AJ1a9r8KPjrqX7R3xZ8W+D/E0vw+0jVhoCW15No1rq0erC0szG5j86RTEIHyDgfNv9hXp3/Cqf2nP+i7R/wDhHaf/APH6LDPPv2FI7GLw38UItM0iXw/aL8R9aEGkzxrFJYRiK2227RozohiHyFVYqMYBIxXHftI2o+Inxa0X4dfAm01TTPiho8xn1PxLZLLY6fpGl6kg+0NeMUEd2bhQpQICxZMCQMpQ+w/smfD74jfDux+I1j8R1aa61XxvqWqW2ovHDAdThnSJTdiGF3WFZWQsI+NucVe0Xwt8T/G37SN94+8YW134d8IeCrOXSvDlit0h/ti4vB/pF/MLeRgYggAjjkyQdjYR1cUW0sK+tzwPXdHli0yz/YT+AdlfWdjZW0SeN/FN5A8Udlp96TJMI2kUCa71DcwXbmMK2yP5QzQ9T4m00/seePbTxh4A0WW7+GXiZbDTfEeh6XGZbjS9QjxbWmpW8CfeFwNsU4CgySAElpGUVpWv7PnxE8QfAvxx8JfFN9cQX1h4m1DU/AmrNftNdLDFKLrTpZZg7yKRMXRt53qpyACFNbvi/wCFHxbfVfh78cvDEVinxQ0q3sdI8W2UNz5Wnavpc7KLxGdgoH2dyZoyASACAJGSNSWGfZMbiWNZFBAcBgGBVgDzyDgg+x5FPooqiD//0f3UoooroOcKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//9k="

        var paramters = ["imagetype":"2","image":base64String]
        Alamofire.Manager.sharedInstance.session.configuration.HTTPAdditionalHeaders = ["apikey":"e6a34edc9cae321d7919d40931e4c497"]
        
        Alamofire.request(.POST, GlobalVariables.baiduOCRUrl, parameters: paramters,encoding:ParameterEncoding.TEXT)
            .debugLog()
            .responseString(encoding: NSUTF8StringEncoding) { (_, _, jsonStr, _) -> Void in
                DataManager.jsParser(jsonStr!)
            }
        }
    
    
    static func jsParser(json:String)
    {
        let context = JSContext()
        let JSON = context.objectForKeyedSubscript("JSON")
        let JSONparse = JSON.objectForKeyedSubscript("parse")
        let JSONString = json
        let parsed = JSONparse.callWithArguments([JSONString])
        var parsedDict = parsed.toDictionary()
        println(parsedDict)
    }
    
    
}




